### ISSUE TITLE
Accepting changes in Track changes package

### ISSUE THREAD

**Issue by VidhyaApple** [rioderaca/LaTeX-Track-Changes#1]
Am using Track Changes package in my latex document.

To use this package `\usepackage{trackchanges}` and Latex document will be `Robinson, \change[ym]{old}{new}, \add[novi]{Thing 1 \& Thing 2, }\add[ym]{Humpty Dumpty}`

To accept all the changes `\usepackage[finalnew]{trackchanges}`. Accepting changes will be reflected only in PDF output.

Now my question is, Is there any way to remove all the track changes tags in latex document too?

Expectation: Accepting changes in both PDF output and in latex document(i.e.without track change tags(`\add{}` or `\change{}` etc..))

Latex document should be like `Robinson, new, Thing 1 \& Thing 2, Humpty Dumpty`

**Comment by rioderaca** [comment]
Hi,

thanks for you comment. Yes, in the TrackChanges package there is a python program that allows you to visualise those tags in the text and accept or reject them, i.e. removing the tags from the LaTeX code.

Hope this helps.

Regards,
Cristian

**Comment by VidhyaApple** [comment]
Thank you so much. Its perfect.. And one more query, In the pythonpackage folder, acceptchanges.py and trackchanges.py programs are there. Can I know how to to trackchanges.py ?  Because to get the track changed document I need to type the tags manually (\add or \change or \remove) . So, Just I assume that trackchanges.py program is for comparing old and new latex files and it itself putting the tags in it. Or Is there any way to out tags on its own?
